spring.application.name=devcoder
server.port=8090
server.address=0.0.0.0
spring.thymeleaf.cache=false

spring.datasource.url=jdbc:mysql://localhost:3306/devcoder?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
